version: '3'

services:
   nextjs:
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - '8010:8020'
      env_file:
         - .env.local
         - .env
      restart: always
